apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: nginx
    name: nginx
    namespace: old
  spec:
    clusterIP: 172.20.73.27
    clusterIPs:
    - 172.20.73.27
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
    selector:
      app: nginx
kind: List
metadata: {}
