apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chris-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chris530/github_actions.git
    targetRevision: main
    path: helm/chris-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: old
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
